### ISSUE TITLE
UserStory 6 - Connect a database

### ISSUE THREAD

**Issue by Alina-Rosenbusch** [Alina-Rosenbusch/Capstone-Arena-App#10]
## Value Proposition

**As a** User
**I want to** use a database 
**in order to** reach my data from different devices 
​

## Description

Exchange data between devices and the database. 
​

## Acceptance Criteria

- [ ] a database for the bookings 
- [ ] a database for the arenas 
- [ ] both pages Home and Arena Overview ​should show the data correctly

## Tasks

- [ ] create a new branch 
- [ ] create a database in MonogoDB (until now filled with the mock data, will be later replaced with real ones) 
- [ ] link the database to the project to show the data in the pages

**Comment by FlorianNova** [comment]
lgtm
