### ISSUE TITLE
UserStory 7 - Booking Form

### ISSUE THREAD

**Issue by Alina-Rosenbusch** [Alina-Rosenbusch/Capstone-Arena-App#14]
## Value Proposition

**As a** User
**I want to** be able enter data to a form 
**in order to** book a training slot in an arena 
​

## Description

![Image](https://github.com/Alina-Rosenbusch/Capstone-Arena-App/assets/134265568/d1437fd6-ae1c-4b46-8706-ca60c44bb2af)

​

## Acceptance Criteria

- [ ] A form provides input-fields for title, an arena, an booking person, a time span and a date 
- [ ] a button can be clicked to save the data
- [ ] clicking the save-button will lead to the homepage
- [ ] a button leads back to the homepage

      ​

## Tasks

- [ ] create a branch
- [ ] create a component 
- [ ] write a form with a text, a calendar, two time, a dropdown menu, and a checkbox
- [ ] implement the form with input fields, ensuring user input can be captured.
- [ ] create an API route that establishes the connection to the MongoDB Atlas database 
- [ ] write a submit handler and
- [ ] add a "Submit" button at the end of the form that submits the data to the API route and triggers the database connection
- [ ] add a "Back" button that allows users to return to the start page

**Comment by Roland-Hufnagel** [comment]
Hi. That's a useful feature and a good story. But some things you can improve:
- In the value proposition you should either say ``so that...``or  `ìn order to...`` (not both).
- I have no idea what the bottom in your wireframe can be
- The acceptance criteria should describe the functionality, that can be checked by someone else in the QA. So please describe the functionality in this way: ``A form provides input-fields for title, name, ...``, ``A button can be clicked to save the data``, ``Clicking the save-button will lead to the homepage``
- 'link the form to the database' is not enough detailed. You can say: ``Write an API-route (pages/api/booking/index.js) that receives the form data and stores it to the database``, ``write a submit handler, that sends the form data to the API``

**Comment by ekat-br** [comment]
Hi Alina, looks almost perfect to me. Just one little thing: In the acceptance criteria you don't mention the "Back Button". Please add this and post your US again :)

**Comment by ekat-br** [comment]
lgtm
