### ISSUE TITLE
UserStory 9 - Bookings sorted by Date

### ISSUE THREAD

**Issue by Alina-Rosenbusch** [Alina-Rosenbusch/Capstone-Arena-App#18]
## Value Proposition

**As a** User
**I want to** see today's bookings and then in descending order 
**in order to** have an immediate overview of the latest bookings
​

## Description

![Image](https://github.com/Alina-Rosenbusch/Capstone-Arena-App/assets/134265568/a8112b20-d2a0-4786-96b2-7a3f9455fa6c)

​

## Acceptance Criteria

- [ ] the bookings are arranged in order of date 
      ​

## Tasks

- [ ] write a function to sort the bookings by date 
- [ ] implement the logic into current rendering

**Comment by Kheirah** [comment]
Just to make sure, the story speaks of a descending order of dates but the image shows _an ascending order_, from 18.7 to 20.7.

To get our teminology straightened out, when the dates ascend, they increase. A descending order would be the reverse, from 20.7 to 18.7. The dates descent, they decrease.

In case you plan to implement to sort the dates in both directions, all good!
In case you want to only sort in one direction, ascending is up, descending is down =)
