### ISSUE TITLE
UserStory 10 - Bookings up to date

### ISSUE THREAD

**Issue by Alina-Rosenbusch** [Alina-Rosenbusch/Capstone-Arena-App#19]
## Value Proposition

**As a** User
**I want to** see only bookings that are up to date
**in order to** be able to see which arena is booked the next days and today
​

## Description

![Image](https://github.com/Alina-Rosenbusch/Capstone-Arena-App/assets/134265568/4cfd73f9-fe75-46f1-9500-8e7a84a61edb)

​

## Acceptance Criteria

- [ ] bookings are shown if they are in the future
- [ ] past one are deleted
      ​

## Tasks

- [ ] write a function which checks which date we have currently and if the bookings were before or after that date 
- [ ] implement the logic into the code

**Comment by Frank-Schaeske** [comment]
Hi Alina, you mention "today" in your value proposition, but your acceptance criteria and tasks only cover the future and the past.
