### ISSUE TITLE
UserStory 1

### ISSUE THREAD

**Issue by Alina-Rosenbusch** [Alina-Rosenbusch/Capstone-Arena-App#2]
## Value Proposition

**As a** User   
**I want to** see a list of booked entries and want to be greeted by the app 
**in order to** see which arena I book at which timeslot
​

## Description

![Image](https://github.com/Alina-Rosenbusch/Capstone-Arena-App/assets/134265568/c24dc77b-beae-4d20-a84e-a27edcb4df9f)

​

## Acceptance Criteria

- [ ] a list of booked arenas 
- [ ] a greeting with my name at the top of the app
      ​

## Tasks

- [ ] create branch 'feature/Home-booked-arena-list'
- [ ] render a list of bookings
- [ ] Greeting shown at the top of the app

**Comment by Roland-Hufnagel** [comment]
Great! 🎉 You got it!
