### ISSUE TITLE
UserStory 2 - List of Arenas

### ISSUE THREAD

**Issue by Alina-Rosenbusch** [Alina-Rosenbusch/Capstone-Arena-App#3]
## Value Proposition

**As a** User  
**I want to** see a list of all arenas 
**so that/in order to** to see which exist 
​

## Description

![Image](https://github.com/Alina-Rosenbusch/Capstone-Arena-App/assets/134265568/bdcc8621-8fa0-4794-a996-34a10572ccce)

​

## Acceptance Criteria

- [ ] a headline with "arena Overview" is shown
- [ ] see a list of all arenas in the stable 

      ​

## Tasks

- [ ] create a branch 'feature/arenalist' 
- [ ] create an dummy array with all arenas that should be displayed 
- [ ] create a component for the list 
- [ ] write the list in the component 
- [ ] create a header with the title of the page which should be "Arena Overview"

**Comment by CorneliusMoe** [comment]
LGTM :)
