### ISSUE TITLE
UserStory 3 - Navigation

### ISSUE THREAD

**Issue by Alina-Rosenbusch** [Alina-Rosenbusch/Capstone-Arena-App#4]
## Value Proposition

**As a** User
**I want to** click at an symbol in the navigation bar
**so that/in order to** move to the arena list

## Description

![Image](https://github.com/Alina-Rosenbusch/Capstone-Arena-App/assets/134265568/1fb09ecb-222f-4f36-b382-5bed6fccd1ea)

​

## Acceptance Criteria

- [ ] a list of symbols at the bottom of the page 
- [ ] clicking at the symbols you can switch between the pages 
      ​

## Tasks

- [ ] create a branch with the name 'feature/navigation' 
- [ ] create a component for the navigation bar 
- [ ] import the router to the component 
- [ ] link the pages to the navigation bar 
- [ ] implement the navigation bar to both pages

**Comment by oliverhees** [comment]
LGTM :)
