### ISSUE TITLE
UserStory 4 - Delete entries

### ISSUE THREAD

**Issue by Alina-Rosenbusch** [Alina-Rosenbusch/Capstone-Arena-App#8]
## Value Proposition

**As a** User
**I want to** to click a button
**so that/in order to** delete wrong or unused entries  
​

## Description

![Image](https://github.com/Alina-Rosenbusch/Capstone-Arena-App/assets/134265568/ccc9c53b-4d87-4856-876b-3ec87dbdfa29)

​

## Acceptance Criteria

- [ ] a delete button in each entry 
- [ ] entry will be deleted from the List when clicking the button 
- [ ] when no entries are there anymore, and empty message is 
shown
      ​

## Tasks

- [ ] Create a branch 
- [ ] create a delete button 
- [ ] link it to every element of the list 
- [ ] implement the functionality of deleting to the button with the id of the entry
- [ ] write an "no entry" message and implement it to show when no 
entries are there

**Comment by FlorianNova** [comment]
lgtm
