### ISSUE TITLE
UserStory 5 - Delete Entries - Confirming of delete

### ISSUE THREAD

**Issue by Alina-Rosenbusch** [Alina-Rosenbusch/Capstone-Arena-App#9]
## Value Proposition

**As a** User
**I want to** click the delete button 
**so that/in order to** finally delete the entry 
​

## Description

![Image](https://github.com/Alina-Rosenbusch/Capstone-Arena-App/assets/134265568/0fd004ab-d882-4f54-9bec-9ddcdf181f8e)

​

## Acceptance Criteria

- [ ] clicking on the delete button opens an other modal 
- [ ] showing a message that the entry is successfully deleted 
- [ ] the message disappears after a few seconds automatically 
- [ ] the entry is deleted 
      ​

## Tasks

- [ ] create a new branch 
- [ ] create a delete button 
- [ ] implement the functionality of deleting the entry 
- [ ] create a new component for the delete message 
- [ ] implement that the message disappears after a few seconds
